name: weather
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dartz: ^0.10.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartx: ^1.2.0
  flutter_screenutil: ^5.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/weather_icon.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

